### ISSUE TITLE
《民事起诉状》中出现重复的【2021年6月】，这个时间是不是写错了呀？

### ISSUE THREAD

**Issue by BuptStEve** [hax/heshijun_v_360#22]
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/11501493/232401761-fcaf1741-f870-4ccf-a675-b739e4724342.png">

**Comment by iamqiz** [comment]
写错了, 前面应该是2020年6月

**Comment by baungo** [comment]
你们眼睛真尖

**Comment by 413476019** [comment]
确实，这块我也没看懂
