### ISSUE TITLE
我来泼盆冷水吧

### ISSUE THREAD

**Issue by LeeWiHong** [hax/heshijun_v_360#30]
其实就是部门裁撤而已，解除劳动合同一般只能是给到N+1的，拿不到更多的，除非是合同有特殊约定但这个情况基本上不可能；
不知道你这个N+1有没有拿到，你这个劳动仲裁能争取的也只有这个N+1的，奖金那些不一定能有的；
看了你后面写的那些遭遇，你自己也写了后面再找工作HR会跟360说那里的事，其实这件事已经对你自己有反噬了，你公开的越多对自己的反噬越大已经对自己再找工作不利了；
劳动这个官司不知道是不是二审终审制，如果是这样的话甭说你还拿不到那个赔偿，你就算是拿到了那个赔偿你也是杀人一万自损一万；
你公开的这么多其实效果不大，围观在这里的都没有那个审判的决策权力，都只能吃瓜而已，而且360的法务养着也不是吃素的，也不会因为你个人的这点公开能给大BOSS多大的伤害；
收拾收拾自己的心情去找下一份工作吧，看你这个工资也是个大佬，没必要一直纠缠在这个地方，你的前方还有比360更广阔的天地

**Comment by LeeWiHong** [comment]
> 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？

嗯  不知名的阿猫阿狗泼冷水而已，你自己去看他写的这个东西 你看他公开这些能从中得到什么利益不？我说了他在这个事上只能争取那个N+1 没有说全部放弃吧？你应该认清一个现实 二审终审制 言外之意 他都已经全输了，明白？？？

**Comment by LeeWiHong** [comment]
> 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？

另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发

**Comment by riverchu** [comment]
精致的利己主义者？人家就算只是单纯的想让大家知道他感觉到的不公不可以吗？只有忍辱负重是好的？

**Comment by wuhanstudio** [comment]
> > 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？
> 
> 另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发

权利要靠自己争取，而不是等人施舍。

正是因为大家都不敢发声，施暴者才越发肆无忌惮。
请不要打击勇敢争取权利的人。

大佬的形象不会因为敢于发声而受到影响，反而是懦弱的人不会收到尊敬。

**Comment by LeeWiHong** [comment]
> 精致的利己主义者？人家就算只是单纯的想让大家知道他感觉到的不公不可以吗？只有忍辱负重是好的？

他所做的这些利己了没？？你去看看那个判决书，他也请了律师了，二审了都是输的，不公？去了解一下法律吧

**Comment by riverchu** [comment]
> > 精致的利己主义者？人家就算只是单纯的想让大家知道他感觉到的不公不可以吗？只有忍辱负重是好的？
> 
> 他所做的这些利己了没？？你去看看那个判决书，他也请了律师了，二审了都是输的，不公？去了解一下法律吧

表示自己**感觉到的不公**，懂吗？感觉到不公不能说吗？你这么维护是不是觉得国内法治环境已经没有什么可改进的空间了？还是觉得之前从没有过冤假错案？

**Comment by riverchu** [comment]
> > > > 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？
> > > 
> > > 
> > > 另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发
> > 
> > 
> > 权利要靠自己争取，而不是等人施舍。
> > 正是因为大家都不敢发声，施暴者才越发肆无忌惮。 请不要打击勇敢争取权利的人。
> > 大佬的形象不会因为敢于发声而受到影响，反而是懦弱的人不会收到尊敬。
> 
> 劳动法规定了的啊，你还能争取到比法规定的更多的东西吗？这哪是什么懦弱勇敢的问题啊，他都已经二审终审了，终了， 他这样的大佬随随便便去搞点其他的都把那几十万赚回来了，真没必要纠结到这里

别随便替人觉得值或不值，人家有权力表达自己的想法，你没资格劝人家闭嘴

**Comment by LeeWiHong** [comment]
> > > 精致的利己主义者？人家就算只是单纯的想让大家知道他感觉到的不公不可以吗？只有忍辱负重是好的？
> > 
> > 
> > 他所做的这些利己了没？？你去看看那个判决书，他也请了律师了，二审了都是输的，不公？去了解一下法律吧
> 
> 表示自己**感觉到的不公**，懂吗？感觉到不公不能说吗？你这么维护是不是觉得国内法治环境已经没有什么可改进的空间了？还是觉得之前从没有过冤假错案？

首先这里只讲这件事实，而不要去牵扯什么国内法治问题，在这件事上，公不公只有依据劳动法可以讲清楚，他自己也请了律师，所以并不存在什么法院对他公不公的问题，如果他还觉得不公那就是他请的那个律师不行

**Comment by wuhanstudio** [comment]
> > > > 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？
> > > 
> > > 
> > > 另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发
> > 
> > 
> > 权利要靠自己争取，而不是等人施舍。
> > 正是因为大家都不敢发声，施暴者才越发肆无忌惮。 请不要打击勇敢争取权利的人。
> > 大佬的形象不会因为敢于发声而受到影响，反而是懦弱的人不会收到尊敬。
> 
> 劳动法规定了的啊，你还能争取到比法规定的更多的东西吗？这哪是什么懦弱勇敢的问题啊，他都已经二审终审了，终了， 他这样的大佬随随便便去搞点其他的都把那几十万赚回来了，真没必要纠结到这里

中国的宪法都可以随意修改，你有没有想过劳动法是否合理？中国的劳动法保护的是谁的利益？

法律并不是完美的，正是勇敢的抗争，才让劳动法有机会一步步完善。

**Comment by zhangchao-wooc** [comment]
有些人跪的久了，脊梁便弯了。有些人站着，却被认为是怪异的行为，便要劝他继续跪着！在提供的资料为真实的前提下，我支持贺老！

**Comment by LeeWiHong** [comment]
> > > > > 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？
> > > > 
> > > > 
> > > > 另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发
> > > 
> > > 
> > > 权利要靠自己争取，而不是等人施舍。
> > > 正是因为大家都不敢发声，施暴者才越发肆无忌惮。 请不要打击勇敢争取权利的人。
> > > 大佬的形象不会因为敢于发声而受到影响，反而是懦弱的人不会收到尊敬。
> > 
> > 
> > 劳动法规定了的啊，你还能争取到比法规定的更多的东西吗？这哪是什么懦弱勇敢的问题啊，他都已经二审终审了，终了， 他这样的大佬随随便便去搞点其他的都把那几十万赚回来了，真没必要纠结到这里
> 
> 别随便替人觉得值或不值，人家有权力表达自己的想法，你没资格劝人家闭嘴

他都可以这样公开发出来，那见着就能有权利发表自己的看法吧，而至于他听不听那是他的事吧，你也不能限制我的言论自由是不是？更何况我所说的还是站在他的位置替他着想的吧？你们呼喊要他勇敢，我是希望他冷静  我也没有伤害他吧

**Comment by LuciNyan** [comment]
> 有些人跪的久了，脊梁便弯了。有些人站着，却被认为是怪异的行为，便要劝他继续跪着！在提供的资料为真实的前提下，我支持贺老！

是的，但是君子不立于危墙之下

**Comment by riverchu** [comment]
> > > > 精致的利己主义者？人家就算只是单纯的想让大家知道他感觉到的不公不可以吗？只有忍辱负重是好的？
> > > 
> > > 
> > > 他所做的这些利己了没？？你去看看那个判决书，他也请了律师了，二审了都是输的，不公？去了解一下法律吧
> > 
> > 
> > 表示自己**感觉到的不公**，懂吗？感觉到不公不能说吗？你这么维护是不是觉得国内法治环境已经没有什么可改进的空间了？还是觉得之前从没有过冤假错案？
> 
> 首先这里只讲这件事实，而不要去牵扯什么国内法治问题，在这件事上，公不公只有依据劳动法可以讲清楚，他自己也请了律师，所以并不存在什么法院对他公不公的问题，如果他还觉得不公那就是他请的那个律师不行

你这不还是说法律没有改进空间吗？这种大话都敢说？真是狂妄自大
还有，你还泼冷水。。。泼给所有不像你那样懦弱闭嘴的人吗？

**Comment by riverchu** [comment]
> > > > > > 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？
> > > > > 
> > > > > 
> > > > > 另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发
> > > > 
> > > > 
> > > > 权利要靠自己争取，而不是等人施舍。
> > > > 正是因为大家都不敢发声，施暴者才越发肆无忌惮。 请不要打击勇敢争取权利的人。
> > > > 大佬的形象不会因为敢于发声而受到影响，反而是懦弱的人不会收到尊敬。
> > > 
> > > 
> > > 劳动法规定了的啊，你还能争取到比法规定的更多的东西吗？这哪是什么懦弱勇敢的问题啊，他都已经二审终审了，终了， 他这样的大佬随随便便去搞点其他的都把那几十万赚回来了，真没必要纠结到这里
> > 
> > 
> > 别随便替人觉得值或不值，人家有权力表达自己的想法，你没资格劝人家闭嘴
> 
> 他都可以这样公开发出来，那见着就能有权利发表自己的看法吧，而至于他听不听那是他的事吧，你也不能限制我的言论自由是不是？更何况我所说的还是站在他的位置替他着想的吧？你们呼喊要他勇敢，我是希望他冷静 我也没有伤害他吧

你觉得你在劝他的话，那我就复用你的逻辑劝你闭嘴，别老当网络“工贼”，你的老板看不到

**Comment by LeeWiHong** [comment]
> 



> 

我不会再跟你讲这种敏感问题，我只讲当下的这件有关劳动的事，其他的一律免谈

**Comment by LeeWiHong** [comment]
> > 劳动法规定了的啊，你还能争取到比法规定的更多的东西吗？这哪是什么懦弱勇敢的问题啊，他都已经二审终审了，终了， 他这样的大佬随随便便去搞点其他的都把那几十万赚回来了，真没必要纠结到这里
> 
> > 首先这里只讲这件事实，而不要去牵扯什么国内法治问题，在这件事上，公不公只有依据劳动法可以讲清楚，他自己也请了律师，所以并不存在什么法院对他公不公的问题，如果他还觉得不公那就是他请的那个律师不行
> 
> 中国的宪法都可以随意修改，你有没有想过劳动法是否合理？中国的劳动法保护的是谁的利益？
> 
> 法律并不是完美的，正是勇敢的抗争，才让劳动法有机会一步步完善。

我不会碰你这个敏感问题的，我只讲当下这个劳动的事

**Comment by ylc395** [comment]
虽然同情博主，但是当他在网络上[笑话其他劳动者的岗位“不是市场制造出来的”“慢性毒药”的时候](https://zhuanlan.zhihu.com/p/49555513)，有没有想到自己被大公司抛弃的这一天呢。只能说社达者得到了应有的下场吧🤔

**Comment by LeeWiHong** [comment]
> 有些人跪的久了，脊梁便弯了。有些人站着，却被认为是怪异的行为，便要劝他继续跪着！在提供的资料为真实的前提下，我支持贺老！

你可以支持他，但你不要随便给要他冷静的人扣帽子，这帽子还是你自己带着好

**Comment by LeeWiHong** [comment]
> > > > > > > 你是？ 什么猫猫狗狗都能出来泼冷水了？张张嘴就劝人家不要在乎各方面的损失？
> > > > > > 
> > > > > > 
> > > > > > 另外一点，越是他这样的大佬，沾上这种事你觉得对他维护个人形象是好事还是坏事？你不要只从你个人情绪上面出发
> > > > > 
> > > > > 
> > > > > 权利要靠自己争取，而不是等人施舍。
> > > > > 正是因为大家都不敢发声，施暴者才越发肆无忌惮。 请不要打击勇敢争取权利的人。
> > > > > 大佬的形象不会因为敢于发声而受到影响，反而是懦弱的人不会收到尊敬。
> > > > 
> > > > 
> > > > 劳动法规定了的啊，你还能争取到比法规定的更多的东西吗？这哪是什么懦弱勇敢的问题啊，他都已经二审终审了，终了， 他这样的大佬随随便便去搞点其他的都把那几十万赚回来了，真没必要纠结到这里
> > > 
> > > 
> > > 别随便替人觉得值或不值，人家有权力表达自己的想法，你没资格劝人家闭嘴
> > 
> > 
> > 他都可以这样公开发出来，那见着就能有权利发表自己的看法吧，而至于他听不听那是他的事吧，你也不能限制我的言论自由是不是？更何况我所说的还是站在他的位置替他着想的吧？你们呼喊要他勇敢，我是希望他冷静 我也没有伤害他吧
> 
> 你觉得你在劝他的话，那我就复用你的逻辑劝你闭嘴，别老当网络“工贼”，你的老板看不到

别骂人

**Comment by kaih001** [comment]
> 其实就是部门裁撤而已，解除劳动合同一般只能是给到N+1的，拿不到更多的，除非是合同有特殊约定但这个情况基本上不可能； 不知道你这个N+1有没有拿到，你这个劳动仲裁能争取的也只有这个N+1的，奖金那些不一定能有的； 看了你后面写的那些遭遇，你自己也写了后面再找工作HR会跟360说那里的事，其实这件事已经对你自己有反噬了，你公开的越多对自己的反噬越大已经对自己再找工作不利了； 劳动这个官司不知道是不是二审终审制，如果是这样的话甭说你还拿不到那个赔偿，你就算是拿到了那个赔偿你也是杀人一万自损一万； 你公开的这么多其实效果不大，围观在这里的都没有那个审判的决策权力，都只能吃瓜而已，而且360的法务养着也不是吃素的，也不会因为你个人的这点公开能给大BOSS多大的伤害； 收拾收拾自己的心情去找下一份工作吧，看你这个工资也是个大佬，没必要一直纠缠在这个地方，你的前方还有比360更广阔的天地

看了判决书，没啥高级的，全都是围绕考勤这个low点，这样一个公司，这样一个大佬，围绕这样一个low点，不知道是不是悲哀，哎，反正刚好给我们这些普通人学习学习和前车之鉴。

**Comment by LeeWiHong** [comment]
> 



> > 其实就是部门裁撤而已，解除劳动合同一般只能是给到N+1的，拿不到更多的，除非是合同有特殊约定但这个情况基本上不可能； 不知道你这个N+1有没有拿到，你这个劳动仲裁能争取的也只有这个N+1的，奖金那些不一定能有的； 看了你后面写的那些遭遇，你自己也写了后面再找工作HR会跟360说那里的事，其实这件事已经对你自己有反噬了，你公开的越多对自己的反噬越大已经对自己再找工作不利了； 劳动这个官司不知道是不是二审终审制，如果是这样的话甭说你还拿不到那个赔偿，你就算是拿到了那个赔偿你也是杀人一万自损一万； 你公开的这么多其实效果不大，围观在这里的都没有那个审判的决策权力，都只能吃瓜而已，而且360的法务养着也不是吃素的，也不会因为你个人的这点公开能给大BOSS多大的伤害； 收拾收拾自己的心情去找下一份工作吧，看你这个工资也是个大佬，没必要一直纠缠在这个地方，你的前方还有比360更广阔的天地
> 
> 看了判决书，没啥高级的，全都是围绕考勤这个low点，这样一个公司，这样一个大佬，围绕这样一个low点，不知道是不是悲哀，哎，反正刚好给我们这些普通人学习学习和前车之鉴。

是啊 也是没办法的，改变不了的，改变不了 只能躲的

**Comment by kaih001** [comment]
> > 
> 
> > > 其实就是部门裁撤而已，解除劳动合同一般只能是给到N+1的，拿不到更多的，除非是合同有特殊约定但这个情况基本上不可能； 不知道你这个N+1有没有拿到，你这个劳动仲裁能争取的也只有这个N+1的，奖金那些不一定能有的； 看了你后面写的那些遭遇，你自己也写了后面再找工作HR会跟360说那里的事，其实这件事已经对你自己有反噬了，你公开的越多对自己的反噬越大已经对自己再找工作不利了； 劳动这个官司不知道是不是二审终审制，如果是这样的话甭说你还拿不到那个赔偿，你就算是拿到了那个赔偿你也是杀人一万自损一万； 你公开的这么多其实效果不大，围观在这里的都没有那个审判的决策权力，都只能吃瓜而已，而且360的法务养着也不是吃素的，也不会因为你个人的这点公开能给大BOSS多大的伤害； 收拾收拾自己的心情去找下一份工作吧，看你这个工资也是个大佬，没必要一直纠缠在这个地方，你的前方还有比360更广阔的天地
> > 
> > 
> > 看了判决书，没啥高级的，全都是围绕考勤这个low点，这样一个公司，这样一个大佬，围绕这样一个low点，不知道是不是悲哀，哎，反正刚好给我们这些普通人学习学习和前车之鉴。
> 
> 是啊 也是没办法的，改变不了的，改变不了 只能躲的

所以对咱们来说，应该感谢大佬，能发出来让普通人学习学习，对于他自己，他肯定已经想好了

**Comment by LeeWiHong** [comment]
> > > > > 精致的利己主义者？人家就算只是单纯的想让大家知道他感觉到的不公不可以吗？只有忍辱负重是好的？
> > > > 
> > > > 
> > > > 他所做的这些利己了没？？你去看看那个判决书，他也请了律师了，二审了都是输的，不公？去了解一下法律吧
> > > 
> > > 
> > > 表示自己**感觉到的不公**，懂吗？感觉到不公不能说吗？你这么维护是不是觉得国内法治环境已经没有什么可改进的空间了？还是觉得之前从没有过冤假错案？
> > 
> > 
> > 首先这里只讲这件事实，而不要去牵扯什么国内法治问题，在这件事上，公不公只有依据劳动法可以讲清楚，他自己也请了律师，所以并不存在什么法院对他公不公的问题，如果他还觉得不公那就是他请的那个律师不行
> 
> 你这不还是说法律没有改进空间吗？这种大话都敢说？真是狂妄自大 还有，你还泼冷水。。。泼给所有不像你那样懦弱闭嘴的人吗？

我不跟谈无稽之谈的东西，只说这个事实

**Comment by LeeWiHong** [comment]
> 



> > > 虽然同情博主，但是当他在网络上[笑话其他劳动者的岗位属于“不是市场制造出来的”“慢性毒药”的时候](https://zhuanlan.zhihu.com/p/49555513)，有没有想到四年后自己被大公司抛弃的这一天呢。只能说社达者得到了应有的下场吧🤔
> > 
> > 
> > 额。。。你想表达
> 
> 我想表达如果博主比较热衷这些市场制造出来的东西，那么自己部门受到裁撤，也只是典型的市场下的遭遇罢了

其实以他自己的人设，随随便便去搞点其他的就流量变现了，几十万随便就搞回来了，没必要，这个会让他吸粉却也对他有反噬，而且职场路会越来越难走的

**Comment by wuhanstudio** [comment]
> 随随便便去搞点其他的就流量变现了，几十万随便就搞回来了，没必要

工资被拖欠的农民工纷纷点了赞，不就是几十万工资嘛，我不要了。

万一老板我干活是要收工资的，下一份工作都不好找了。

**Comment by galenjiang** [comment]
> > 
> 
> > > > 虽然同情博主，但是当他在网络上[笑话其他劳动者的岗位属于“不是市场制造出来的”“慢性毒药”的时候](https://zhuanlan.zhihu.com/p/49555513)，有没有想到四年后自己被大公司抛弃的这一天呢。只能说社达者得到了应有的下场吧🤔
> > > 
> > > 
> > > 额。。。你想表达
> > 
> > 
> > 我想表达如果博主比较热衷这些市场制造出来的东西，那么自己部门受到裁撤，也只是典型的市场下的遭遇罢了
> 
> 其实以他自己的人设，随随便便去搞点其他的就流量变现了，几十万随便就搞回来了，没必要，这个会让他吸粉却也对他有反噬，而且职场路会越来越难走的

流量什么？人家搞技术标准的，一步一个脚印。

**Comment by ylc395** [comment]
> > > 
> > 
> > 
> > > > > 虽然同情博主，但是当他在网络上[笑话其他劳动者的岗位属于“不是市场制造出来的”“慢性毒药”的时候](https://zhuanlan.zhihu.com/p/49555513)，有没有想到四年后自己被大公司抛弃的这一天呢。只能说社达者得到了应有的下场吧🤔
> > > > 
> > > > 
> > > > 额。。。你想表达
> > > 
> > > 
> > > 我想表达如果博主比较热衷这些市场制造出来的东西，那么自己部门受到裁撤，也只是典型的市场下的遭遇罢了
> > 
> > 
> > 其实以他自己的人设，随随便便去搞点其他的就流量变现了，几十万随便就搞回来了，没必要，这个会让他吸粉却也对他有反噬，而且职场路会越来越难走的
> 
> 流量什么？人家搞技术标准的，一步一个脚印。

技术标准？很显然，在hax最喜欢的市场经济下，由于他的原雇主并不需要一个搞技术标准的人，把他开除是合情合理的。如果他尊重市场，应当尽快想办法在国内外找到一个愿意购买他的雇主，而不是上网发小作文

**Comment by wuhanstudio** [comment]
> 技术标准？很显然，在hax最喜欢的市场经济下，由于他的原雇主并不需要一个搞技术标准的人，把他开除是合情合理的。如果他尊重市场，应当尽快想办法在国内外找到一个愿意购买他的雇主，而不是上网发小作文

友情提醒：下次被开除记得多为雇主着想，切勿恶意讨薪，被开除是合情合理的。

**Comment by ylc395** [comment]
> > 技术标准？很显然，在hax最喜欢的市场经济下，由于他的原雇主并不需要一个搞技术标准的人，把他开除是合情合理的。如果他尊重市场，应当尽快想办法在国内外找到一个愿意购买他的雇主，而不是上网发小作文
> 
> 友情提醒：下次被开除记得多为雇主着想，切勿恶意讨薪，被开除是合情合理的。

你去看看 hax 的这篇雄文吧 https://zhuanlan.zhihu.com/p/49555513 ，看看 hax 会不会觉得你是同志💦

**Comment by wuhanstudio** [comment]
> 你去看看 hax 的这篇雄文吧 https://zhuanlan.zhihu.com/p/49555513 ，看看 hax 会不会觉得你是同志💦

请问你觉得这篇文章不合理的地方在哪里？

**Comment by ylc395** [comment]
> > 你去看看 hax 的这篇雄文吧 https://zhuanlan.zhihu.com/p/49555513 ，看看 hax 会不会觉得你是同志💦
> 
> 他说年轻人要找一些能成长的工作，不要在安检等 重复体力性劳动 的工作安于现状，直至被淘汰。
> 
> 请问你觉得这篇文章不合理的地方在哪里？

要不是全文里反复强调“要淘汰”、“市场至上”的论点，我还真信这是一篇针砭时弊的文章，而不是一篇自我感觉良好的爹味说教文章。事到如今，轮到作者自己被市场淘汰了，又有什么话好说呢？只能怪自己的安于现状，做了重复性工作（话说参加标准委员会的周期性会议，和他看不起的安检员在地铁站里集合开晨会，恐怕也没有什么本质区别）吧

**Comment by wuhanstudio** [comment]
我现在在英国，导师一周只来学校工作2天，其他时间居家办公，安于现状，只是重复性教学科研工作。

如果我导师在国内，理当就被 “淘汰” 了，不知道这样说能不能让你意识到是国内制度和公司的问题？

**Comment by ylc395** [comment]
> 哈哈，划重点：
> 
>     * 居家办公 = 安于现状
> 
>     * 参加委员会的周期性会议，和地铁站里集合换班，没有本质区别。

你不会觉得很好笑吧😄。无论吹出花来，最后都是被淘汰😄
事实上，可能当年嘲笑过的安检员还在做安检，而作者现在失业了写小作文，确实哈哈了💦

**Comment by galenjiang** [comment]
> 

谁告诉你工作被拒了🟰找不到工作？
人家有的是选择机会，而你等到这天的时候，估计只有地铁安检工作吧

**Comment by lingr7** [comment]
考勤这种东西，本来公司方面就是有全面的数据，普通打工人，怎么可能拿到真实的原始数据，只有自己作为认证，能确认一些重要的日子的，上班考勤点，当然只有公司方的所谓证据了。人证因为记忆不精准和相比物品不客观没有被才行，但是物证就客观吗？原始数据就真实有效，公司想操作这些数据还不简单。

**Comment by jiechen257** [comment]
> 

哥们，看你这么客观的讨论真的感觉像是在给大厂裁员洗地啊。人家大佬发声不公，是非对错大家都看得出来，结果如何已经不重要了，别人只是把不舒服的点公之于众顺便给360挖坑，你在这一个劲的就结果无用论的说，然后让人家啥都不做，多少有点人血馒头的感觉

**Comment by LeeWiHong** [comment]
> > 
> 
> 哥们，看你这么客观的讨论真的感觉像是在给大厂裁员洗地啊。人家大佬发声不公，是非对错大家都看得出来，结果如何已经不重要了，别人只是把不舒服的点公之于众顺便给360挖坑，你在这一个劲的就结果无用论的说，然后让人家啥都不做，多少有点人血馒头的感觉

你是没经历过裁员吧？好话歹话都分不清了吗？

**Comment by galenjiang** [comment]
> > > 
> > 
> > 
> > 谁告诉你工作被拒了🟰找不到工作？ 人家有的是选择机会，而你等到这天的时候，估计只有地铁安检工作吧
> 
> 我无所谓啊，我也没看不起任何工作。你不会觉得你的这个回复有啥攻击性吧

好好学学语文吧，我的重点是工作被拒了 不🟰 找不到工作。还有分清楚地铁安检和外卖小哥的职业还是有点区别的，你细品。
