### ISSUE TITLE
借个楼讨论下近期关于开源的一些感想【chatGPT，github copilot】

### ISSUE THREAD

**Issue by huashiyiqike** [hax/heshijun_v_360#57]
人工智能做得好的地方，都是训练数据充分完备的领域，比如绘画，编程，自然语言。

ChatGPT训练语料包含微软github数据库，从而赋予了人工智能强大的逻辑和代码能力。

有试用过相关的辅助代码生成工具，确实挺震撼的。而且现在还是比较早期的阶段，前两年也说AI画画效果差不可能替代人工，很快就被打脸了。再过几年，也许大部分的代码功能都不需要人来实现了。

开源代码也可以随意被用来训练编程AI，即使推出新的license形式，公开代码也很难被版权保护。

开源有没有可能是程序员的自掘坟墓？

我承认开源有很大的价值，和全球大佬交流代码也能进步。我要讨论的不是开源对个人的影响，而是我们的行业壁垒问题，开源让AI更容易的学会我们的领域知识，这个在其他行业是不常见的，除了少数像艺术这种本身必须需要公开内容的行业。开放源代码并不是必须的。从未来职业发展来看，最终可能导致少数精英获益，而大多数普通人最终受损，比如被更强大的AI抢饭碗。

毕竟一个可以毫无怨言007，24小时满负荷工作，分分钟写出千万行代码，从不摸鱼不请假，成本低廉无需五险一金，不会删库跑路，不会和公司有任何纠纷的coder，只要将来验证能力到位，资本家有什么理由不优先选用呢。

**Comment by DaoNetease** [comment]
所以就要选择闭门造车么？

**Comment by tonyqus** [comment]
你这思路不对，请问你现在日常用的哪个工具或者软件没有开源项目的影子？比如音视频播放器用的都是ffmpeg库，前端三大库（react, angular, vue）全部是开源。开源本身没有问题，应该鼓励。

问题出在使用的人或者公司和他们本应遵守的开源准则，当然国内就没有什么信用和准则可言，导致了很多人误以为开源就是免费白嫖，不需要付费，甚至不需要提及用了哪些开源组件，正是因为这些人才使得开源作者更加艰难，但开源确实就是目前软件行业的核心生产力的重要组成部分，没有开源可能整个软件行业的发展会慢很多。

> 再过几年，也许大部分的代码功能都不需要人来实现了。
你可能对ChatGPT有很多误解，Demo确实很震撼，但实际使用下来限制很多，直接根据需求写代码更是无从谈起，我不知道你是如何得出这个结论的，如果只是看到了它能够写个网站出来就认为它能够代替人类程序员，那你可能真的是被忽悠了。太多细节无法实现，改Bug就别想了。

**Comment by zzy-life** [comment]
chatGPT只能用来提供思路，而且它只有写工具方法的正确率较高，如果有上下文联系代码都是错的，都需要自己来改

**Comment by zzy-life** [comment]
> > chatGPT只能用来提供思路，而且它只有写工具方法的正确率较高，如果有上下文联系代码都是错的，都需要自己来改
> 
> 你说的对，现在模型的输入token数量有比较大的限制，但是这只是暂时的。

如果AI能发展到独立生成完整的工程性系统，我觉得那时候的社会生产力也不会低，生产力足够高的情况下社会福利应当也会提高，也会产生新的职业

**Comment by tonyqus** [comment]
> 我自己也开源了很多代码

你开源的代码放哪了？为啥github是空的？

**Comment by huashiyiqike** [comment]
> > 我自己也开源了很多代码
> 
> 你开源的代码放哪了？为啥github是空的？@huashiyiqike

https://github.com/huashiyiqike/LSTM-MATLAB

**Comment by tonyqus** [comment]
@huashiyiqike 我看了下你的开源项目和commit情况，似乎好多年没有commit了。开源项目主要还是靠坚持，很多时候做开源就是很孤独的，那些热门的开源项目也不是一直火的，过了火热的时期你是否还能坚持是个问题。

我觉得你应该研究下怎么做好开源？等你的开源火了再来谈会不会失业，其实答案很明显，等你的开源火了你是不愁找不到工作的，我给你举个最近的例子，Apache committee委员会成员张磊，从阿里跳槽到微软，直接汇报给微软的Tech Fellow，年薪150万+RMB，他是因为在kubernetes社区的突出贡献，以及对dapr项目进入CNCF的推动，进入微软的。

**Comment by huashiyiqike** [comment]
> @huashiyiqike 我看了下你的开源项目和commit情况，似乎好多年没有commit了。开源项目主要还是靠坚持，很多时候做开源就是很孤独的，那些热门的开源项目也不是一直火的，过了火热的时期你是否还能坚持是个问题。
> 
> 我觉得你应该研究下怎么做好开源？等你的开源火了再来谈会不会失业，其实答案很明显，等你的开源火了你是不愁找不到工作的，我给你举个最近的例子，Apache committee委员会成员张磊，从阿里跳槽到微软，直接汇报给微软的Tech Fellow，年薪150万+RMB，他是因为在kubernetes社区的突出贡献，以及对dapr项目进入CNCF的推动，进入微软的。

我承认开源有很大的价值，和全球大佬交流代码也能进步。我要讨论的不是开源对个人的影响，而是我们的行业壁垒问题，开源让AI更容易的学会我们的领域知识，这个在其他行业是不常见的，除了少数像艺术这种本身必须需要公开内容的行业。开放源代码并不是必须的。从未来职业发展来看，最终可能导致少数精英获益，而大多数普通人最终受损，比如被更强大的AI抢饭碗。

**Comment by QianYu13** [comment]
> 

我试用了一下，还是有待提升吧只能说，于有工作的人来说是很棒的东西，但是对于学生党来说还是自己学来得靠谱，ai这个东西确实好用啊，以前搜个问题搜半天，国内的计算机情况也是有目共睹，闭门造车嘛，很多问题得不到答案，但是ai能聚合分析给出问题答案，这无疑是好的，有利有弊吧只能说，我作为学生党确实这个东西帮我解答了很多找不到的bug，bingai的搜索也带来了便利，普通人会被淘汰，但是普通人便宜啊，没办法，恶性循环，就像网上到处吹，不行，大学入党是假的，大学有压迫，学生要奋起反抗，人家一句勒令退学就把你压回来了，你怎么敢拿前途去赌，只能说，智商提高的同时也要提高大众的情商，总不能叫停研发吧

**Comment by strawbreey** [comment]
> > @huashiyiqike 我看了下你的开源项目和commit情况，似乎好多年没有commit了。开源项目主要还是靠坚持，很多时候做开源就是很孤独的，那些热门的开源项目也不是一直火的，过了火热的时期你是否还能坚持是个问题。
> > 我觉得你应该研究下怎么做好开源？等你的开源火了再来谈会不会失业，其实答案很明显，等你的开源火了你是不愁找不到工作的，我给你举个最近的例子，Apache committee委员会成员张磊，从阿里跳槽到微软，直接汇报给微软的Tech Fellow，年薪150万+RMB，他是因为在kubernetes社区的突出贡献，以及对dapr项目进入CNCF的推动，进入微软的。
> 
> 我承认开源有很大的价值，和全球大佬交流代码也能进步。我要讨论的不是开源对个人的影响，而是我们的行业壁垒问题，开源让AI更容易的学会我们的领域知识，这个在其他行业是不常见的，除了少数像艺术这种本身必须需要公开内容的行业。开放源代码并不是必须的。从未来职业发展来看，最终可能导致少数精英获益，而大多数普通人最终受损，比如被更强大的AI抢饭碗。

为什么要考虑被AI抢饭碗呢？假设数据是公开的，那么任何人都可以通过AI完成大部分工作，人会被AI取代，但是任何人也可以利用AI进行创新。比如，假设前公司有10个人，现在把九个人开除，但是开除的9个人也可以利用AI 抄底前公司，并且干掉他。最后，几个公司都可能存在，因为他们系统的服务本身还是细分方向

**Comment by huashiyiqike** [comment]
@strawbreey 你挺乐观的，希望以后更多有差异化的需求吧。普通的cruder, 调参侠，切图仔是目前占大多数的岗位需求，以后可能需要更多prompter，finetuner。重新学吧。从汇编到c到python到自然语言编程，未来人人都可以编程，就像现在人人都可以画画，编程技能就不值钱了

**Comment by hoochanlon** [comment]
* [毛泽东选集.第五卷（高清版）.pdf](https://github.com/hax/heshijun_v_360/files/11301374/default.pdf)
* [cp859q20.pdf](https://github.com/hax/heshijun_v_360/files/11301376/cp859q20.pdf)

**Comment by tonyqus** [comment]
@huashiyiqike 你是不是墙内新闻看太多了，我看真的挺焦虑的，从开贴你就在贩卖焦虑，你要做的就是摆脱墙内环境，多看看英文的技术分析，简中媒体都少看。

**Comment by huashiyiqike** [comment]
> @huashiyiqike 你是不是墙内新闻看太多了，我看真的挺焦虑的，从开贴你就在贩卖焦虑，你要做的就是摆脱墙内环境，多看看英文的技术分析，简中媒体都少看。

@tonyqus 你可以下个Cursor玩一玩

**Comment by strawbreey** [comment]
> @strawbreey 你挺乐观的，希望以后更多有差异化的需求吧。普通的cruder, 调参侠，切图仔是目前占大多数的岗位需求，以后可能需要更多prompter，finetuner。重新学吧。从汇编到c到python到自然语言编程，未来人人都可以编程，就像现在人人都可以画画，编程技能就不值钱了

你可能需要转变思维，曾经就差一个程序员的梗现在可能因为gpt变成就差一个idea。未来社会不管千变万化，但本质还是信息不对称带来的价值差。只要你能创造价值，那么价值就值钱，如果价值真到忽略不计的时候，记得拿起武器捍卫你的土地。

**Comment by tonyqus** [comment]
> > @huashiyiqike 你是不是墙内新闻看太多了，我看真的挺焦虑的，从开贴你就在贩卖焦虑，你要做的就是摆脱墙内环境，多看看英文的技术分析，简中媒体都少看。
> 
> @tonyqus 你可以下个Cursor玩一玩

这玩意只能在mac上面跑。。。好像没法普及，等1年后看看这个东西活得好不好，我感觉就是个蹭热度产品
