### ISSUE TITLE
劳动诉讼与开源运动中的领导权问题 —— 由 Hax 与 360 劳动争议诉讼展开的讨论

### ISSUE THREAD

**Issue by ufo5260987423** [hax/heshijun_v_360#80]
毫无疑问，任何运动的实质一定是 “依靠谁” 和 “为了谁” 的问题，这个问题决定一切。因为它是第一性的，并且决定了我们在一切问题上持有怎样的观点和态度。Hax 与 360 公司几年来的劳动争议诉讼似乎标明了一种情况，就是开发者的绝对领导地位被一些组织窃取了。这种地位是由开发者们的实践、数量和运动热情所决定的，但是一旦遇到一些好处，最终的受益者似乎并非贡献者群体，一旦遇到一些困难，倒是开源参与的个人要受到波及。说好的资本承担风险呢？收益的时候盆满钵满，遇到困难优先把人裁员？

Hax 是帮助 360 参与开源并实现劳动雇佣中企业要求的实际收益了的，不然 360 不会正常发工资；但当企业想要不履行相关合同，随便一个由头就能扫地出门，还要败坏职业声誉。而 Hax 在劳动诉讼问题上的优柔寡断，“担心本案对人们参与标准和开源事业的热情产生负面影响”，显然应该归咎于普遍的全体开源开发者的动摇和犹豫。于是这就是他暂时得到的一个结果 “没有从这个具体的司法案件中感受到公平正义”。如果他一个高级打工仔不能得到，那么作为群体的所有开源参与者都得不到。

这全部问题的实质就在于：开源运动在中国所促进的伟大的轰轰烈烈的互联网行业乃至于非互联网行业的革命，全部没有展现它们的诚意。在给予有限的经济地位之后，对于创造财富的劳动没有起码的尊重。从开源运动的一开始直到今天，许多企业口头上是 “开源的” 实际行动上是反开源的，总是考虑 “开源” 是否对自己的市场地位和盈利能力造成影响，对于开源社区半是虚情假意，半是口蜜腹剑；个人去做开源的时候，反而要以微薄的个人工资对冲无限可能的风险。更别提这种风险多数是由企业的市场和非市场行为产生的。

这就是领导权丧失以后产生的矛盾。从中如果读者不能学到在循规蹈矩遵守企业制度之外的任何事情，那么开源运动就完了。如果学到了一点东西，那就应该知道首先要建立某种牢固的不可动摇的领导权：要么是开源运动的实质性解体，让企业和企业支持的 “KPI 开源” 占据运动的全部；要么一切权力归参与开源运动的自然人本身。

开源运动只有全心全意的保护大多数参与开发和使用开源软件的自然人的权力，才能无条件得到这些大多数人的支持，并且对于侵犯社区的现象坚决回击甚至主动出击。有的企业想要活 102 年，但是20 年前的企业和今天完全不同； 102 岁的老人和 102 年前一样，是完整的对社会具有贡献的个人。也就是说，只有全心全意依靠广大参与开源工作的自然人，开源运动才不会犹豫、动荡和摇摆，才不会放任 Hax 身上那样的悲剧不断发生在普通人身上。

要实现这样的目的，就必须对整个的包括开源基金会在内的组织、开源中国在内的宣传和所有的个人来一个根本性的改造。这样的行动目前还很幼稚，比如 Web3.0 基础上的去中心化社区；但是这样的行动目前还在进行。我们不要在 “监督” 的名义下通过一些软弱无力的决议和建议；我们一定要自己亲手去实践，把开源的领导权全部归参与开源的自然人，从自己亲身的实践中，学会正确地分配一切。

**Comment by hoochanlon** [comment]
订阅基本毛选看看

* [毛泽东选集.第五卷（高清版）.pdf](https://github.com/hax/heshijun_v_360/files/11301374/default.pdf)
* [cp859q20.pdf](https://github.com/hax/heshijun_v_360/files/11301376/cp859q20.pdf)
