### ISSUE TITLE
参考：问题不在考勤，也在考勤

### ISSUE THREAD

**Issue by vietor** [hax/heshijun_v_360#81]
我之前公司开始时是弹性时间的，但因一个同事的操作，变成了固定时间。
这同事持续性的每日中午到，整个上午任何人都找不到他，领导找他谈过让他至少10点到，他还是我行我素。最后政策变了，他感觉被针对，就走了。

**Comment by vietor** [comment]
既然把事情摊开，至少也说一下别人不知道的前因后果。

**Comment by tonyqus** [comment]
总有老鼠屎坏了一锅好汤
